theme = "onedark_transparent"

[editor]
line-number = "relative"
bufferline  = "always"
rulers      = [80]
mouse       = true
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
